In [8]:
import pandas as pd

data ={
    "TID": [1,2,3,4,5,6,7,8,9,10],
    "Refund" :["Yes" , "No" ,"No" ,"Yes","No" ,"No", "Yes","No" ,"No" ,"No" ],
    "Marital Status" : ["Single " ,"Married", "Single ","Married" ,"Divorced","Married","Divorced","Single " ,"Married","Single " ],
    "Taxable Income " : ["125K","100K","70K","120K","95K","60K","220K","85K","75K","90K"],
    "Cheat" : ["No","No","No","No","Yes","No","No","Yes","No","Yes"]
}
df = pd.DataFrame(data)
print(df)

   TID Refund Marital Status Taxable Income  Cheat
0    1    Yes        Single             125K    No
1    2     No        Married            100K    No
2    3     No        Single              70K    No
3    4    Yes        Married            120K    No
4    5     No       Divorced             95K   Yes
5    6     No        Married             60K    No
6    7    Yes       Divorced            220K    No
7    8     No        Single              85K   Yes
8    9     No        Married             75K    No
9   10     No        Single              90K   Yes

In [9]:
df.loc[[0,4,7,8]]

   TID Refund Marital Status Taxable Income  Cheat
0    1    Yes        Single             125K    No
4    5     No       Divorced             95K   Yes
7    8     No        Single              85K   Yes
8    9     No        Married             75K    No

In [10]:
df.iloc[2:8]

   TID Refund Marital Status Taxable Income  Cheat
2    3     No        Single              70K    No
3    4    Yes        Married            120K    No
4    5     No       Divorced             95K   Yes
5    6     No        Married             60K    No
6    7    Yes       Divorced            220K    No
7    8     No        Single              85K   Yes

In [11]:
df.iloc[4:9,2:5]

  Marital Status Taxable Income  Cheat
4       Divorced             95K   Yes
5        Married             60K    No
6       Divorced            220K    No
7        Single              85K   Yes
8        Married             75K    No

In [12]:
df.iloc[:,1:4]

  Refund Marital Status Taxable Income
0    Yes        Single             125K
1     No        Married            100K
2     No        Single              70K
3    Yes        Married            120K
4     No       Divorced             95K
5     No        Married             60K
6    Yes       Divorced            220K
7     No        Single              85K
8     No        Married             75K
9     No        Single              90K

In [13]:
df1 = pd.read_csv("/content/Iris.csv")
df1.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [14]:
df1.drop(df1.index[3], inplace=True)
df1.drop(df1.columns[2], axis=1, inplace=True)
print(df1)

      Id  SepalLengthCm  PetalLengthCm  PetalWidthCm         Species
0      1            5.1            1.4           0.2     Iris-setosa
1      2            4.9            1.4           0.2     Iris-setosa
2      3            4.7            1.3           0.2     Iris-setosa
4      5            5.0            1.4           0.2     Iris-setosa
5      6            5.4            1.7           0.4     Iris-setosa
..   ...            ...            ...           ...             ...
145  146            6.7            5.2           2.3  Iris-virginica
146  147            6.3            5.0           1.9  Iris-virginica
147  148            6.5            5.2           2.0  Iris-virginica
148  149            6.2            5.4           2.3  Iris-virginica
149  150            5.9            5.1           1.8  Iris-virginica

[149 rows x 5 columns]

In [15]:
df2=pd.read_csv("/content/employees.csv")
print(df2.shape)
df2.info()
df2.describe()

(5, 10)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 10 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee_ID          5 non-null      int64
 1   Name                 5 non-null      object
 2   Department           5 non-null      object
 3   Age                  5 non-null      int64
 4   Salary               5 non-null      int64
 5   Years_of_Experience  5 non-null      int64
 6   Joining_Date         5 non-null      object
 7   Gender               5 non-null      object
 8   Bonus                5 non-null      int64
 9   Rating               5 non-null      float64
dtypes: float64(1), int64(5), object(4)
memory usage: 532.0+ bytes

,Employee_ID,Age,Salary,Years_of_Experience,Bonus,Rating
count,5.000000,5.000000,5.00000,5.000000,5.0,5.000000
mean,103.000000,34.000000,60000.00000,7.400000,5500.0,4.100000
std,1.581139,5.612486,7905.69415,3.847077,1000.0,0.494975
min,101.000000,28.000000,50000.00000,3.000000,4500.0,3.500000
25%,102.000000,29.000000,55000.00000,4.000000,5000.0,3.800000
50%,103.000000,34.000000,60000.00000,8.000000,5000.0,4.000000
75%,104.000000,38.000000,65000.00000,10.000000,6000.0,4.500000
max,105.000000,41.000000,70000.00000,12.000000,7000.0,4.700000

In [16]:

df2.head()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [17]:
df2.tail(3)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5

In [18]:
df2[["Salary"]].mean()

Salary    60000.0
dtype: float64

In [19]:
df2[["Bonus"]].sum()

Bonus    27500
dtype: int64

In [20]:
df2[["Age"]].min()

Age    28
dtype: int64

In [21]:
df2[["Rating"]].max()

Rating    4.7
dtype: float64

In [22]:
df2.sort_values("Salary",ascending=False)

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5

In [23]:
import pandas as pd
import numpy as np

df2["Performance"] = np.select(
    [
        df2["Rating"] >= 4.5,
        df2["Rating"] >= 4.0
    ],
    [
        "Excellent",
        "Good"
    ],
    default="Average"
)

print(df2)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating Performance
0   2020-03-15  Female   5000     4.5   Excellent
1   2017-07-19    Male   7000     4.0        Good
2   2013-06-01    Male   6000     3.8     Average
3   2021-02-10  Female   4500     4.7   Excellent
4   2010-11-25    Male   5000     3.5     Average

In [24]:
df2.isnull()

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
0,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False

In [25]:
df2.rename(columns={"Employee_ID":"ID"})

,ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
0,101,Alice,HR,29,50000,4,2020-03-15,Female,5000,4.5,Excellent
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average
3,104,Diana,Marketing,28,55000,3,2021-02-10,Female,4500,4.7,Excellent
4,105,Edward,Sales,38,60000,12,2010-11-25,Male,5000,3.5,Average

In [36]:
df2[(df2["Years_of_Experience"] > 5) &(df2["Department"]=="IT")]

,Employee_ID,Name,Department,Age,Salary,Years_of_Experience,Joining_Date,Gender,Bonus,Rating,Performance
1,102,Bob,IT,34,70000,8,2017-07-19,Male,7000,4.0,Good
2,103,Charlie,IT,41,65000,10,2013-06-01,Male,6000,3.8,Average

In [41]:
df2["Tax"] = df2["Salary"]*0.10
print(df2)

   Employee_ID     Name Department  Age  Salary  Years_of_Experience  \
0          101    Alice         HR   29   50000                    4
1          102      Bob         IT   34   70000                    8
2          103  Charlie         IT   41   65000                   10
3          104    Diana  Marketing   28   55000                    3
4          105   Edward      Sales   38   60000                   12

  Joining_Date  Gender  Bonus  Rating Performance     Tax
0   2020-03-15  Female   5000     4.5   Excellent  5000.0
1   2017-07-19    Male   7000     4.0        Good  7000.0
2   2013-06-01    Male   6000     3.8     Average  6500.0
3   2021-02-10  Female   4500     4.7   Excellent  5500.0
4   2010-11-25    Male   5000     3.5     Average  6000.0

In [42]:
df2.to_csv("modified_employee.csv")